before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: N5CePSwJG2ZTS4LiAj2JI9GfqgJjmHdsEveyrB/2phOB2xNsnroZL+nsJk4Vb/SLYmoxUgEvF9Wh6xIIHfC6YP8cQFVnQDKAxOGLezGSzLSh2u15/U6hnAT8idl2Mm0YZQdzuKgy1ZgwssW3c+3syzYjNmWAOtobQb08RuLYDJ+eF5E6HmmyLp+ZUcWQjFcNGui+Qiy0z67J2BSWxjmaRj0xnY05VtXpUGpncqq3LU0FnWTshlqQW8HcvlYJ6baqQLFzx9jRX0OfzU0uiMA+6dD6A07Rqt+s7xsNu2ApC7Jk+qg8nudOQBB3WiWhxK6NjHEO2HthZUg9ihgjk+rh1j7o0Zp4ldefdZnCbMOWGUR1LBVAXmvLasHX0Ji8O/TIv2Lr+K/g2qmk+v4kiBKg1L7/F23Eut1v9hBE1C3e46pKzzUy/GuEEdGnDiAljXA8amVrHayo/P2XZqhfFUzhOJo6m9ECP8BhNkEn9Jjjl+Smkuo0+JnYGo+ZOF3V5ZA7j9Jbd/Q3Dw2btVSv/4IMA+hS3dyHMaWNaFR++0KmHEKtycQGpMEg4s/1zmD86iXdJCuqeFnVIL+gFnxTiBYm9nH4/gaBYwdWHrXtF6Gkh8DIRJgh4ZSmAwfmnr4kwNjK47ciFe0oA+NkTDsiiGveXAO9J2zawp0ZTVJFsQNw73I= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
